# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more inormation see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependecies
        run: npm install

      - name: Build    
        run: npm run build --if-present

      - name: Run tests
        run: npm run test

      - name: Lint
        run: npx eslint src/**/*.ts

      - name: Run ts-prune  
        run: npm run find-deadcode
